DROP TABLE IF EXISTS Member_Offer;
CREATE TABLE Member_Offer(
    ID_MEMBER_OFFER INT NOT NULL AUTO_INCREMENT,
    Id_Member INT,
    Id_Offer INT,
    PRIMARY KEY (ID_MEMBER_OFFER),
    FOREIGN KEY (Id_Member) REFERENCES Member(ID_MEMBER),
    FOREIGN KEY (Id_Offer) REFERENCES Offer(ID_OFFER)
);