version: "3.3"

services:

  aaahostur-api:
    image: aaahostur-api

    ports:
      - 5000:5000

    depends_on:
      - 'aaahosturdbdev'

    restart: always

  aaahosturdbdev:
    image: mysql

    enviroment:
      - MYSQL_ROOT_PASSWORD=sqU4r)p1nd2Sp%ck7xe%inj0
      - MYSQL_DATABASE=aaahosturdbdev

    ports:
      - 3306

    volumes:
      - aaahosturdb:/var/lib/mysql

  aaahosturNginx:
    image: nginx

    ports:
      - 8080:80

    volumes:
      - 'aaahosturServer:/usr/share/nginx/html'

volumes:
  aaahosturdb:
  aaahosturServer: por definir