DROP datatable IF EXISTS Professional_Profile;
CREATE TABLE Professional_Profile (
    ID_PROFESSIONAL_PROFILE INT NOT NULL AUTO_INCREMENT,
    Workplace VARCHAR(512) NOT NULL,
    Address VARCHAR(512) NOT NULL,
    Position VARCHAR(512) NOT NULL,
    Join_Date VARCHAR(256) NOT NULL,
    Id_Member INT NOT NULL,
    PRIMARY KEY (ID_PROFESSIONAL_PROFILE),
    FOREIGN KEY (Id_Member) REFERENCES Member(ID_MEMBER)
);