DROP datatable IF EXISTS Languaje;
CREATE TABLE Languaje(
ID_LANGUAJE INT AUTO INCREMENT NOT NULL,
Name VARCHAR(512) NOT NULL,
Lvl VARCHAR(512) NOT NULL,
Certificate VARCHAR(512) NOT NULL,
PRIMARY KEY (ID_LANGUAJE)
);