DROP TABLE IF EXISTS Languaje;
CREATE TABLE Languaje(
ID_LANGUAJE INT  NOT NULL AUTO_INCREMENT,
Name VARCHAR(512) NOT NULL,
Lvl VARCHAR(512) NOT NULL,
Certificate VARCHAR(512) NOT NULL,
PRIMARY KEY (ID_LANGUAJE)
);