DROP TABLE IF EXISTS Qualification;
CREATE TABLE Qualification(
ID_QUALIFICATION INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(512) NOT NULL,
Description VARCHAR(512) NOT NULL,
Id_Qualification_Parent INT,
Id_Job_Category INT,
PRIMARY KEY (ID_QUALIFICATION),
FOREIGN KEY (Id_Qualification_Parent) REFERENCES Qualification(ID_QUALIFICATION),
FOREIGN KEY (Id_Job_Category) REFERENCES Job_Category(ID_JOB_CATEGORY)
);